import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import QRCode from 'react-qr-code'
import QRcodeLink from 'qrcode';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [link, setLink] = useState('');
  const [qrcodeLink, setQrcodeLink] = useState('');

  const handleGenerate = (link) => {
    QRcodeLink.toDataURL(link, {
      width: 600,
      margin:3,
    }, function(err, url){
      setQrcodeLink(url)
    })
  }

  const handleQrcode = (e) =>{
    setLink(e.value);
    handleGenerate(e.value)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <QRCode
         value={link}
        />
        <input
         className={styles.input}
         placeholder='Digita o seu link'
         value={link}
         onChange={(e) => {handleQrcode(e.target)}}
        />
        <a href={qrcodeLink} download={`qrcode.png`}>Baixar QRCode</a>
      </main>
    </>
  )
}
